[package]
name = "gamelife"
version = "0.1.0"
edition = "2021"

[dependencies]
crossterm = "0.28.1"
log = "0.4.22"
noise = "0.9.0"
ratatui = { version = "0.28.1", features = ["all-widgets"] }
simplelog = "0.12.2"
